spring.application.name=hospital-management
spring.profiles.active=dev
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.root=INFO
logging.level.com.hospital.management=INFO
spring.main.lazy-initialization=true
